### ISSUE TITLE
Textboxes Cannot Be Typed In on Linux

### ISSUE THREAD

**Issue by zicklag** [armory3d/armory2d#10]
I am trying to use Armory2D on Linux and I am unable to type into text boxes. Interestingly I can backspace if there is already text in the textbox, but I can't type any new characters into it. This might actually be an issue with Zui now that I think of it.

**Comment by TriVoxel** [comment]
Same here actually. I am working on a big(ish) game at the moment and this feature will be crucial for the development. I hope this can be worked out soon! 😃 By the way, I'm having this issue on the 2.8 branch. Not sure if that makes a difference though.

**Comment by cgvirus** [comment]
Same problem here. Debian Buster/Sid.

**Comment by zicklag** [comment]
I'm going to close this because because it is duplicated by armory3d/armory#888 and it is probably better to track it in that repo. Participants could :+1: that issue to show support.
