### ISSUE TITLE
Menu font size should follow Blender preferences

### ISSUE THREAD

**Issue by DavidLeoni** [armory3d/armory2d#16]
If in Blender you set  Preferences->Interface->Display->Resolution scale you can change menu font size, but this setting is not used by Armory2D (Using Armory 0.6.0 on Ubuntu 16.04 ):  

![image](https://user-images.githubusercontent.com/628313/52177306-4ddbd480-27bf-11e9-8272-2c6de7df1210.png)

**Comment by luboslenco** [comment]
Oh yes that would be handy, right now there is only a separate `UI Scale` setting in Armory add-on preferences.

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armory/issues/3091.
