### ISSUE TITLE
"Import Assets" crashes armory2d

### ISSUE THREAD

**Issue by blackno666** [armory3d/armory2d#18]
Win 10:
In Armory2d switch to "Assets" tab in top right corner. Press "Import Asset". Armory2d will crash.

**Comment by luboslenco** [comment]
Fixed at https://github.com/armory3d/armory2d/commit/46fefda5ded7d59a4cda426f4fb4d4f83f8ce07e https://github.com/armory3d/armory_tools/commit/ee5fb8e26166a1de910d5b85d6790b12270d8784.
