### ISSUE TITLE
Assets: cannot drag&drop fonts

### ISSUE THREAD

**Issue by blackno666** [armory3d/armory2d#19]
Win10:
Switching to "Assets" tab. Try to drag and drop a .ttf or .otf font to the drag and drop area. Nothing will happen.

**Comment by MoritzBrueckner** [comment]
I think the issue is that Kha doesn't seem to accept files with upper case endings like `.TTF` in which windows font files are stored (compared to files ending with `.ttf`). Can you confirm that ".ttf" files work?
