### ISSUE TITLE
"_" (Underbar) cannot be entered.

### ISSUE THREAD

**Issue by Sandy10000** [armory3d/armory2d#30]
"_" (Underbar) cannot be entered when entering an element name and event name.When using code that uses an element name or event name with an underscore, the code must be corrected.

**Comment by BlackGoku36** [comment]
<img width="230" alt="Screen Shot 2019-09-30 at 11 28 32 AM" src="https://user-images.githubusercontent.com/36535717/65852961-82ffed00-e375-11e9-9074-6476437d20a6.png">
I can enter "_", if that what you meant

**Comment by Sandy10000** [comment]
Is the difference in OS affected? I'm using Linux mint but I can't enter it.

For example, when a new progress bar is added, it is named Progress_bar. In this case, an underscore is entered.If I delete this character and try to enter name with underscore using my keyboard, I cannot enter the underscore.

os: linux mint
blender: 2.80
armory: git version

**Comment by BlackGoku36** [comment]
I am using MacOS, so might be linux issue, can't speak for windows

**Comment by BlackGoku36** [comment]
I don't know, this happen on my machine too now. Can't input anything that can be entered with `shift`, e.g., "_", "()", "$", etc. This look like Kromx, issue, because when I tested it, I was using krom that comes with kha.

**Comment by Sandy10000** [comment]
Also reported to Kromx.

**Comment by luboslenco** [comment]
Should be resolved nowadays.
