### ISSUE TITLE
Progress bar does not change on the game screen

### ISSUE THREAD

**Issue by Sandy10000** [armory3d/armory2d#31]
Can get or set the value of the progress bar, but the display does not change.

blender2.8
armory git version
linux mint

**Comment by BlackGoku36** [comment]
i think this has to do with armory2d is not up to date in armory tools.
Because i tried it when i created pb, and it worked with both nodes

**Comment by BlackGoku36** [comment]
Go to `armsdk - lib - armory_tools - armory2d - opengl` and replace `krom.js` with below ones (don't forget to rename it from `txt` to `js`)

[krom.txt](https://github.com/armory3d/armory2d/files/3669115/krom.txt)

and create following logic node:

<img width="850" alt="Screen Shot 2019-09-30 at 11 42 45 AM" src="https://user-images.githubusercontent.com/36535717/65853523-78deee00-e377-11e9-87fe-d703ae688e85.png">

and you should get:
![pb](https://user-images.githubusercontent.com/36535717/65853744-24883e00-e378-11e9-8873-a44ede8a5515.gif)

**Comment by Sandy10000** [comment]
I'm sorry it was my mistake.
I forgot to connect to the max terminal.
