### ISSUE TITLE
Animations and timeline

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/armory2d#32]
I am starting to add animation for canvas elements, I am adding something like this:
<img width="242" alt="Screen Shot 2019-09-30 at 5 29 45 PM" src="https://user-images.githubusercontent.com/36535717/65876870-f0c50c80-e3a7-11e9-8898-ce8e0b4396d5.png">

@luboslenco  Should i use other existing tweening library for this? or should I create small one?

*keep this open, till I implement it*

**Comment by BlackGoku36** [comment]
I already got something:

https://send.firefox.com/download/25f1b6dca36f2aab/#7SNUVGSij1rsje81cYc7Hg

**Comment by BlackGoku36** [comment]
I tried to use lewis's racoon library tweening and it work good. But then where should I put the tweening code? In it own file(e.g: tween.hx) or put everything in canvas.hx

**Comment by luboslenco** [comment]
Ideally the tweening would run on  [iron/Tween](https://github.com/armory3d/iron/blob/master/Sources/iron/system/Tween.hx) ([example](https://github.com/armory3d/armory_examples/blob/master/tween/Sources/arm/MyTrait.hx)) for consistency with iron/armory. But that is not accessible right now either. Maybe it's time to tie armory2d directly with iron/armory repositories, and stop being a pure kha library?

**Comment by BlackGoku36** [comment]
That would be cool! And btw, what do you mean by `tie armory2d directly with iron/armory repositories`? like having armory2d as source code in iron/armory3d and run Armory2d from armory like Krom player?

**Comment by mundusnine** [comment]
I would personally prefer armory2d be a kha library. The reasoning is armory2d could be used for UI design with zui if it remains untied to armory3d.

I am also biased as I would find armory2d to be a good solution to use with foundry2d(2d game engine). 
I think better way would maybe be to make a generalized Tweening library for kha based projects ? 

That way we could use the same code base across Kha based FOSS projects/engines. Like for foundry I use the same concept as armory for scripting I.e. with Traits. If we could generalize a subset of core concepts used in armory I think we could make a viable and extendable eco-system.

Anyways, just my take.

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armory/issues/3091.
