### ISSUE TITLE
Canvas Editor not Working on mac

### ISSUE THREAD

**Issue by Hibyehello** [armory3d/armory2d#58]
When I open the Canvas editor it shows this 
<img width="401" alt="Screen Shot 2020-11-27 at 1 41 39 PM" src="https://user-images.githubusercontent.com/36666883/100547612-58d1e580-322d-11eb-9b03-a13dc5439fb9.png">
I used the precompiled version included in the armorySDK folder and I compiled it myself.
In the console it outputs 

> GL Error 1282 /Users/lubos/Downloads/armorcore/Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c `209`

I think this is where the error is reporting from

<img width="714" alt="Screen Shot 2020-11-29 at 10 40 21 AM" src="https://user-images.githubusercontent.com/36666883/100547959-4ce72300-322f-11eb-8c09-4c7878314e29.png">

**Comment by luboslenco** [comment]
Should be resolved nowadays.
